package com.amrabdelhamiddiab.carouselepoxy

val listOfItems: List<Message> = listOf(
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amr", "adadadadadadadda"),
    Message("amr", "adadadadadadadda"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb"),
    Message("amy", "bvbvbvbbvbvbvbvbvbvbvb")
)
val recentlyActive = listOf(
    Profile(
        0,
        "Jenifer",
        "",
        "2 min ago"
    ),
    Profile(
        1,
        "Marcus",
        "",
        "16 min ago"
    ),
    Profile(
        2,
        "Lisa",
        "",
        "21 min ago"
    )
)